version: 2.1

orbs:
  node: circleci/node@7

executors:
  machine:
    machine:
      docker_layer_caching: true
      image: ubuntu-2204:current

workflows:
  test:
    jobs:
      - node/test:
          name: Test with Node.js 22
          executor: machine
          pkg-manager: yarn
          setup:
            - node/install:
                install-yarn: true
                node-version: '22'
            - run:
                name: Build and run docker container
                command: |
                  echo "$LICENSE" | base64 --decode > ./stardog-license-key.bin
                  docker login -u "$ARTIFACTORY_USERNAME" -p "$ARTIFACTORY_PASSWORD" stardog-eps-docker.jfrog.io
                  docker build -t this/here/starduck ./
                  docker run --name stargoose -p 127.0.0.1:5820:5820 -d -it this/here/starduck
